tlshd: fixup compile errors with HAVE_GNUTLS_PSK_ALLOCATE_CREDENTIALS2
Fixes the following compile errors when HAVE_GNUTLS_PSK_ALLOCATE_CREDENTIALS2 is
enabled.

```
client.c:369:40: error: format ‘%c’ expects argument of type ‘char *’,
but argument 4 has type ‘int *’ [-Werror=format=]
  369 |         if (sscanf(identity, "NVMe%01d%c%02d %*s",
      |                                       ~^
      |                                        |
      |                                        char *
      |                                       %lc
  370 |                    &version, &type, &hash) == 3) {
      |                              ~~~~~
      |                              |
      |                              int *
server.c: In function ‘tlshd_tls13_server_psk_handshake’:
server.c:332:55: error: ‘GNUTLS_MAC_NONE’ undeclared
(first use in this function); did you mean ‘GNUTLS_EXT_NONE’?
  332 |                                                       GNUTLS_MAC_NONE);
      |                                                       ^~~~~~~~~~~~~~~
      |                                                       GNUTLS_EXT_NONE

```

Note that `gnutls_psk_allocate_server_credentials2()` accepts one of
`GNUTLS_MAC_UNKNOWN`, `GNUTLS_MAC_SHA256` or `GNUTLS_MAC_SHA384` as the
`mac` argument. Currently, `GNUTLS_MAC_NONE` does not exist in GnuTLS,
this patch changes this invalid type to `GNUTLS_MAC_UNKNOWN`.

Fixes: a5a25e9 ("tlshd: use gnutls_psk_allocate_{client,server}_credentials2")
Signed-off-by: Wilfred Mallawa <wilfred.mallawa@wdc.com>